language: c

os:
  - linux
  - osx

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install cmake

compiler:
  - clang
  - gcc

before_script:
  - mkdir _build
  - cd _build
  - cmake -DWITH_UCI:BOOL=OFF ..
  - make

script:
  - ./chinadns -h
